# Generated by Django 4.0.4 on 2022-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_artist_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
